#!/bin/sh

realpath() {
	echo $(perl -e 'use Cwd "abs_path"; print abs_path(@ARGV[0])' -- "$1")
}

BASEDIR=`dirname "$0"`
DOCKICON=`realpath $BASEDIR/../Resources/dva.icns`
cd $BASEDIR
xattr -dr ./ffmpeg
exec ./jre/Contents/Home/bin/java \
    -Xdock:name=DVA \
    -Xdock:icon=$DOCKICON \
    -Dlog4j2.contextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector \
    -Xmx1G \
    -jar DVA.jar "$@"
